#!/bin/bash
##
## This is a configuration file for the jobs.
##
## Create a 'local-configuration' file to override settings.
##

##############################
##       Background         ##
##############################

##
## Configuration for running jobs in the background.
## This is a list of jobs to run
RUN_ALL="ping-ip wget-website traceroute-host local-network speed wifi"

##
## Interval to run the commands in seconds
##
INTERVAL=60

##############################
##        Logging           ##
##############################

## This is the directory where the logs are written to
## The default is to use a relative directory
logs="`dirname \"$0\"`/logs"
#logs="/var/logs/network-monitor"

##
## Time format
##
## The format to use for the date command to format the time
## stamps in the logs
DATE_FORMAT="%a;%F;%T"

##
## Ending of the log files
##
LOG_ENDING=".log.csv"

## The separator between values
SEPARATOR=";"

##############################
##          Ping            ##
##############################
##
## Ping an address and store its result
##

## addresses separated by spaces
PING_ADDRESSES="8.8.8.8"
## Options for the ping command
## Default: ping once
PING_OPTIONS="-c 1 -q"

## Values for success and failure for the statistics
PING_SUCCESS=1
PING_FAILURE=0

##############################
##          wget            ##
##############################
##
## wget is used to ping a website
##

## Websites to ping separated by a space
WGET_WEBSITES="http://detectportal.firefox.com"

## Options for the wget command
## Default: silent and throw away output
WGET_OPTIONS="-q -O /dev/null"

## Values for success and failure for the statistics
WGET_SUCCESS=1
WGET_FAILURE=0

##############################
##       traceroute         ##
##############################
##
## get routing statistics

## how far to hop
TRACEROUTE_HOPS=10

## targets divided by space
TRACEROUTE_HOSTS="8.8.8.8"

## additional options
TRACEROUTE_OPTIONS="-n -q 3"

## default value for timeout
TRACEROUTE_TIMEOUT_IP='?'
## milliseconds
TRACEROUTE_TIMEOUT_MS='0'

##############################
##      local network       ##
##############################
##
## collect statistics about the local network
##

## ethernet addresses to check the status of
MAC_ADDRESSES="98:de:d0:60:92:cf"

## network to have a look at 1-254
MAC_NETWORK="192.168.0"

## options for local ping to gather mac adresses
MAC_PING_OPTIONS="-c 1 -q -W 1"

##############################
##      download speed      ##
##############################
##
## retrieve a file and get the download speed
##

## URL of the file to download
DOWNLOAD_URL="https://raw.githubusercontent.com/niccokunzmann/network-status-monitor/master/1mb"

## Maximum bytes to download
DOWNLOAD_MAX_BYTES="100000"

## Maximum time to spend
DOWNLOAD_MAX_SECONDS=1
